// <auto-generated />
using System;
using ISKI.IBKS.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISKI.IBKS.Persistence.Migrations
{
    [DbContext(typeof(IbksDbContext))]
    [Migration("20260114100829_AddNewEntities")]
    partial class AddNewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.AlarmDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("ExpectedDigitalValue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxThreshold")
                        .HasColumnType("float");

                    b.Property<double?>("MinThreshold")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SensorName");

                    b.ToTable("AlarmDefinitions", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.AlarmEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlarmDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TriggerValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NotificationSent");

                    b.HasIndex("ResolvedAt");

                    b.HasIndex("StationId", "OccurredAt");

                    b.ToTable("AlarmEvents", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.AlarmUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumPriorityLevel")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ReceiveEmailNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("AlarmUsers", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.AlarmUserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlarmDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlarmUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("AlarmDefinitionId", "AlarmUserId")
                        .IsUnique();

                    b.ToTable("AlarmUserSubscriptions", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.Calibration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DbColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Result")
                        .HasColumnType("bit");

                    b.Property<double>("ResultFactor")
                        .HasColumnType("float");

                    b.Property<bool>("ResultSpan")
                        .HasColumnType("bit");

                    b.Property<bool>("ResultZero")
                        .HasColumnType("bit");

                    b.Property<double>("SpanDiff")
                        .HasColumnType("float");

                    b.Property<double>("SpanMeas")
                        .HasColumnType("float");

                    b.Property<double>("SpanRef")
                        .HasColumnType("float");

                    b.Property<double>("SpanStd")
                        .HasColumnType("float");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double>("ZeroDiff")
                        .HasColumnType("float");

                    b.Property<double>("ZeroMeas")
                        .HasColumnType("float");

                    b.Property<double>("ZeroRef")
                        .HasColumnType("float");

                    b.Property<double>("ZeroStd")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Calibrations", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.ChannelInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BrandModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("CalibrationFormulaA")
                        .HasColumnType("float");

                    b.Property<double>("CalibrationFormulaB")
                        .HasColumnType("float");

                    b.Property<double>("ChannelMaxValue")
                        .HasColumnType("float");

                    b.Property<double>("ChannelMinValue")
                        .HasColumnType("float");

                    b.Property<short>("ChannelNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ParameterText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("StationId", "Parameter")
                        .IsUnique();

                    b.ToTable("ChannelInformations", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.DiagnosticType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosticLevel")
                        .HasColumnType("int");

                    b.Property<string>("DiagnosticLevelTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiagnosticTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DiagnosticTypeNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosticTypeNo")
                        .IsUnique();

                    b.ToTable("DiagnosticTypes", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LogTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Level");

                    b.HasIndex("StationId", "LogCreatedDate");

                    b.ToTable("LogEntries", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.PowerOffTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSentToSais")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SentToSaisAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsSentToSais");

                    b.HasIndex("StationId", "StartDate");

                    b.ToTable("PowerOffTimes", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.SampleRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SampleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggerParameter")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SampleCode");

                    b.HasIndex("Status");

                    b.HasIndex("StationId", "StartedAt");

                    b.ToTable("SampleRequests", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AkisHizi")
                        .HasColumnType("float");

                    b.Property<int?>("AkisHizi_Status")
                        .HasColumnType("int");

                    b.Property<double?>("Akm")
                        .HasColumnType("float");

                    b.Property<int?>("Akm_Status")
                        .HasColumnType("int");

                    b.Property<double?>("CozunmusOksijen")
                        .HasColumnType("float");

                    b.Property<int?>("CozunmusOksijen_Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DesarjDebi")
                        .HasColumnType("float");

                    b.Property<int?>("DesarjDebi_Status")
                        .HasColumnType("int");

                    b.Property<double?>("HariciDebi")
                        .HasColumnType("float");

                    b.Property<double?>("HariciDebi2")
                        .HasColumnType("float");

                    b.Property<int?>("HariciDebi2_Status")
                        .HasColumnType("int");

                    b.Property<int?>("HariciDebi_Status")
                        .HasColumnType("int");

                    b.Property<double?>("Iletkenlik")
                        .HasColumnType("float");

                    b.Property<int?>("Iletkenlik_Status")
                        .HasColumnType("int");

                    b.Property<bool>("IsSentToSais")
                        .HasColumnType("bit");

                    b.Property<double?>("Koi")
                        .HasColumnType("float");

                    b.Property<int?>("Koi_Status")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<double?>("Ph")
                        .HasColumnType("float");

                    b.Property<int?>("Ph_Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentToSaisAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Sicaklik")
                        .HasColumnType("float");

                    b.Property<int?>("Sicaklik_Status")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TesisDebi")
                        .HasColumnType("float");

                    b.Property<int?>("TesisDebi_Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsSentToSais");

                    b.HasIndex("StationId", "ReadTime");

                    b.ToTable("SensorDatas", (string)null);
                });

            modelBuilder.Entity("ISKI.IBKS.Domain.Entities.StationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ConductivitySpanDuration")
                        .HasColumnType("int");

                    b.Property<double>("ConductivitySpanReference")
                        .HasColumnType("float");

                    b.Property<int>("ConductivityZeroDuration")
                        .HasColumnType("int");

                    b.Property<double>("ConductivityZeroReference")
                        .HasColumnType("float");

                    b.Property<string>("ConnectionDomainAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConnectionPassword")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConnectionPort")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConnectionUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataPeriodMinute")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDataDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PhSpanDuration")
                        .HasColumnType("int");

                    b.Property<double>("PhSpanReference")
                        .HasColumnType("float");

                    b.Property<int>("PhZeroDuration")
                        .HasColumnType("int");

                    b.Property<double>("PhZeroReference")
                        .HasColumnType("float");

                    b.Property<string>("PlcIpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlcRack")
                        .HasColumnType("int");

                    b.Property<int>("PlcSlot")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SetupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Software")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("StationSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
